
// Throw private exception
throw:Exception message
